# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a9fcf5f173ebb993f3dd9ddbda4accb1fe16843b9a4397ed673aeb0d7e8d730f8a892fa2f36146b65e8a5e3aaf19f5e1ceae78661247541ced6ba202511a7eb

test:
  secret_key_base: 41f371d5ae389e33b964173d4f62e98967b2eb373a6c7db2849971f3be3cbf246d29cccbf222aab78e34e276ccd91aa3305aa99dd73f0442917268f1df23f88f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
